# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/uncertainmove/Document/logism/pipeline/pipeline.cache/wt [current_project]
set_property parent.project_path /home/uncertainmove/Document/logism/pipeline/pipeline.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /home/uncertainmove/Document/dld-master/washmach_design/src/bcd_to_segment.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/display.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/load_use_check.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/regfiles.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/MemWb.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/instruction_translate.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/IF-ID.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/IDEX.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/EXMem.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/data_redirect.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/controller.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/branch.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/ALU.v
  /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/sources_1/new/main.v
  /home/uncertainmove/Document/dld-master/washmach_design/src/integer_to_bcd.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/constrs_1/new/benchmark.xdc
set_property used_in_implementation false [get_files /home/uncertainmove/Document/logism/pipeline/pipeline.srcs/constrs_1/new/benchmark.xdc]


synth_design -top main -part xc7a100tcsg324-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
